import re

ADDRESS_MAX_LENGTH: int = 100
DESCRIPTION_MAX_LENGHT: int = 1024
NAME_MAX_LENGTH: int = 100
PHONE_MAX_LENGTH: int = 30
PHOTO_MAX_LENGTH: int = 256
TG_ID_MAX_LENGTH: int = 50
ROLE_MAX_LENGTH: int = 20
NOTE_MAX_LENGTH = 500
STATUS_MAX_LENGTH = 8
MIN_NUMBER = 1
MIN_LENGTH: int = 5
DEFAULT_REMINDER_MINUTES_BEFORE = 60
CONTENT_TYPE_MAX_LENGTH: int = 100
SKIP = 0
DEFAULT_LIMIT = 100
MAX_LIMIT = 1000
PHONE_PATTERN = re.compile(r'^[0-9+\-\s()]{10,}$')
MAX_FILE_SIZE = 5 * 1024 * 1024
ALLOWED_FORMATS = {'jpg', 'png', 'jpeg'}
SEAT_GT = 0
SEAT_LE = 20
MIN_LENGTH_USERNAME = 2
MIN_LENGTH_PASSWORD = 8
MAX_LENGTH_PASSWORD = 128
PHONE_INVALID_CHARS = re.compile(r'[\s\-\(\)]')
